Update frontend
LiskHQ/lsk-faucet pull request #17
Opened 2024-07-03 09:12 UTC by nagdahimanshu

### What was the problem?

This PR resolves #14 

### How was it solved?

- [ ] Update frontend as per design

### How was it tested?
Local

2024-07-04 13:47 UTC, sameersubudhi requested changes
Looks good and works as expected!
- Can we please make the transaction hash clickable so that it redirects to the block explorer? Perhaps we can take the explorer URL as an flag (`explorer.url`)/env variable where the default is set to https://sepolia-blockscout.lisk.com.
- Let's also add a `explorer.tx.path` flag, defaulting to `tx`
- In addition, let's rename the `token-address` flag to `token.address` for consistency with the remaining flags.

2024-07-05 11:30 UTC, ikem-legend approved these changes

2024-07-05 12:39 UTC, sameersubudhi approved these changes
Works as expected! 👍

2024-07-05 12:52 UTC, sameersubudhi approved these changes

2024-07-05 13:45 UTC, shuse2 approved these changes

2024-07-05 13:45 UTC, merged